#!/bin/bash
sudo apt-get -y --force-yes install vim mc tmux python-pip ntp
echo ""
echo ""
echo "******************************************************"
echo "*                                                    *"
echo "*   You are now ready to go!                         *"
echo "*                                                    *"
echo "*   Run any other script in current directory to     *"
echo "*   install whatever you need.                       *"
echo "*                                                    *"
echo "*                                                    *"
echo "******************************************************"
echo ""
echo ""